### ISSUE TITLE
"Rescan Blocks" causes app to crash 

### ISSUE THREAD

**Issue by JettScythe** [gcash/android-neutrino#21]
Tested on both ASUS_X018D & Samsung Galaxy S7

**Comment by ctvin** [comment]
I am also experiencing this on a Samsung Galaxy S8+. In addition, the wallet never syncs beyond block 0, so it's fundamentally unusable. This is the latest release on Google Play store. It had functioned fine on the same phone with the first release.

**Comment by vinarmani** [comment]
I am also experiencing this on a Samsung Galaxy S8+. In addition, the wallet never syncs beyond block 0, so it's fundamentally unusable. This is the latest release on Google Play store. It had functioned fine on the same phone with the first release.

**Comment by JettScythe** [comment]
Interestingly enough, I can get it to sync if I RPC to my node, but it never shows any confirmed tx that I know should be in the wallet. Effectively no different from having it not sync at all.

**Comment by JettScythe** [comment]
Just tested on a Samsung Galaxy A5 - same problem.

**Comment by JettScythe** [comment]
No issues with rescan blocks with the newest update - just needs to be synced first.
