### ISSUE TITLE
Allow recovering from other mobile wallets (eg. Copay)

### ISSUE THREAD

**Issue by Klakurka** [gcash/android-neutrino#28]
Allow recovering from other mobile wallets (eg. Copay) using a 12-word seed.

**Comment by cpacia** [comment]
So this is using standard bip44 and will technically recover any other seeds that use bip44. However, there is a caveat. The rescan functionality takes an extremely long time, like a minimum a half hour and potentially much more than that if it has to go back to genesis.

**Comment by cpacia** [comment]
Closing because I don't see us changing from anything other than bip44.
